Fixes hanging issue during image building

diff --git a/Dockerfile.cpu b/Dockerfile.cpu
--- a/Dockerfile.cpu
+++ b/Dockerfile.cpu
@@ -34,5 +34,6 @@ RUN conda install python="3.10" -y
 
 WORKDIR /app/stable-diffusion-webui
 
-RUN export TORCH_COMMAND="pip install torch==2.0.0 torchvision==0.15.1" && \
-    bash ./webui.sh --skip-torch-cuda-test --use-cpu all --no-download-sd-model 2>&1 | grep "No checkpoints found." || exit 1
+RUN touch install.log && \
+    timeout 2h bash -c "export TORCH_COMMAND=\"pip install torch==2.0.1 torchvision==0.15.2\" && ./webui.sh --skip-torch-cuda-test --use-cpu all --no-download-sd-model 2>&1 | tee install.log &" && \
+    sleep 5 && while true; do grep -q "No checkpoints found." install.log && exit 0; grep -q "ERROR" install.log && exit 1; sleep 3; done
diff --git a/Dockerfile.cuda b/Dockerfile.cuda
--- a/Dockerfile.cuda
+++ b/Dockerfile.cuda
@@ -34,4 +34,6 @@ RUN conda install python="3.10" -y
 
 WORKDIR /app/stable-diffusion-webui
 
-RUN bash ./webui.sh --skip-torch-cuda-test --no-download-sd-model 2>&1 | grep "No checkpoints found." || exit 1
+RUN touch install.log && \
+    timeout 2h bash -c "./webui.sh --skip-torch-cuda-test --no-download-sd-model 2>&1 | tee install.log &" && \
+    sleep 5 && while true; do grep -q "No checkpoints found." install.log && exit 0; grep -q "ERROR" install.log && exit 1; sleep 3; done
